python3 bert_lstm_ner.py   \
                  --task_name="NER"  \ 
                  --do_train=True   \
                  --do_eval=True   \
                  --do_predict=True
                  --data_dir=/data/bohan/models/BERT-BiLSTM-CRF-NER/data   \
                  --vocab_file=/data/bohan/models/BERT-BiLSTM-CRF-NER/chinese_L-12_H-768_A-12/vocab.txt  \ 
                  --bert_config_file=/data/bohan/models/BERT-BiLSTM-CRF-NER/chinese_L-12_H-768_A-12/bert_config.json \  
                  --init_checkpoint=/data/bohan/models/BERT-BiLSTM-CRF-NER/chinese_L-12_H-768_A-12/bert_model.ckpt   \
                  --max_seq_length=128   \
                  --train_batch_size=16   \
                  --learning_rate=2e-5   \
                  --num_train_epochs=3.0   \
                  --output_dir=./output/result_dir/ 
